### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by ronanguilloux** [naholyr/show-time#1]
``` bash
➜  ~  show-time
/usr/local/lib/node_modules/show-time/cli.js:5
const inquirer = require('inquirer')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
➜  ~  show-time --configure
/usr/local/lib/node_modules/show-time/cli.js:5
const inquirer = require('inquirer')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
➜  ~  node -v
v0.12.7
➜  ~  npm -v
2.11.3
```

**Comment by naholyr** [comment]
The package is marked as requiring node ≥ 4.0. Even if you get through the `const` warnings, you need support of arrow functions. The only real solution is to upgrade your version of node.
As node 4.0 is the official LTS, I do not intend in supporting 0.12, doing my part to spread the love for the new node ;)

**Comment by ronanguilloux** [comment]
OMG, [0.12](https://nodejs.org/en/blog/release/v0.12.0/), this is sooooo february 2015!

Thanks for pointing out how far behind was my nodejs version ;-)

**Comment by naholyr** [comment]
:P sorry for that ^^ but truely it won't be easy to support it so… well sorry
